dist: trusty
sudo: false
language: cpp
compiler: gcc
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before install:
  - pip install --user cpp-coveralls
script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./test/run_test
# after_success:
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
